name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/dependabot.yml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/dependabot.yml"
  workflow_dispatch:

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          install_options: --no-daemon
          extra_nix_config: |
            extra-trusted-substituters = http://127.0.0.1

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@76aaf8814cdb385b86597c32b8c51b66b69b0839 # main@2026-04-15 (node24)
        with:
          use-flakehub: false

      - name: Run zizmor
        run: nix run .#nixosConfigurations.x1.pkgs.zizmor -- --offline --format github .github/workflows
