name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/dependabot.yml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/dependabot.yml"
  workflow_dispatch:

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          install_options: --no-daemon
          extra_nix_config: |
            extra-trusted-substituters = http://127.0.0.1

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@3c034b51a9deec0a09ef1df8b436ac5db50fae94 # main@2026-04-15 (node24)
        with:
          use-flakehub: false

      - name: Run zizmor
        run: nix run .#nixosConfigurations.x1.pkgs.zizmor -- --offline --format github .github/workflows
