name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/dependabot.yml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/dependabot.yml"
  workflow_dispatch:

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          install_options: --no-daemon
          extra_nix_config: |
            extra-trusted-substituters = http://127.0.0.1

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@5626df0a8b8f16cb060538f6d3041500a2d10cb0 # main@2026-04-15 (node24)
        with:
          use-flakehub: false

      - name: Run zizmor
        run: nix run .#nixosConfigurations.x1.pkgs.zizmor -- --offline --format github .github/workflows
